#!/bin/bash -l
# Manpreet 25/07/2026
# Generates c-oe-nav's subs/page-index.md from the oe-frontend-tests sitemap
# crawl - one row per page (area, title, URL, route, reach path), so the kit
# carries every screen's exact address itself instead of pointing at a host-local
# directory that isn't version-controlled. Re-run whenever the crawl is refreshed;
# the sitemap's screenshots stay external (35M, not worth vendoring).

abort() {
    echo >&2 '
****************************
*** ABORTED DUE TO ERROR ***
****************************
'
    date
    echo "An error occurred. Exiting..." >&2
    exit 1
}

trap 'abort' 0
set -e

sitemap_root="" # override with -s/--sitemap-root, defaults to ~/oe-frontend-tests/docs/sitemap

while [[ $# -gt 0 ]]; do
    p="$1"
    case $p in
    -s | --sitemap-root)
        sitemap_root="${2}"
        shift
        ;;
    *)
        echo "Invalid Parameter ... exiting" && exit 1
        ;;
    esac
    shift # move to next parameter
done

##################################################
### VARIABLES (See end of script for execution) ##
##################################################

skill_root="$(dirname "$(dirname "$(realpath "$0")")")"
sitemap_root="${sitemap_root:-${HOME}/oe-frontend-tests/docs/sitemap}"
sitemap_index="${sitemap_root}/sitemap.index.json"
page_index="${skill_root}/subs/page-index.md"

##################################################
### CHECKS (See end of script for execution)    ##
##################################################

echo -e "\nStarting Pre-flight checks ..."
echo "-------------------------------"

echo "Checking sitemap index exists..."
[ -f "${sitemap_index}" ] || { echo "Sitemap index not found at ${sitemap_index} (pass -s/--sitemap-root)"; exit 1; }
echo "[OK]"

echo "Checking jq is available..."
command -v jq >/dev/null || { echo "jq is required"; exit 1; }
echo "[OK]"

echo "Checks complete ..."
echo "-------------------------------"

##################################################
### FUNCTIONS (See end of script for execution) ##
##################################################

writeHeader() {
    local version areas pages
    version="$(jq -r '.oeVersion' "${sitemap_index}")"
    areas="$(jq -r '.totalAreas' "${sitemap_index}")"
    pages="$(jq -r '.totalPages' "${sitemap_index}")"

    cat > "${page_index}" <<-HEADER
	# Page index - every screen's exact address

	Generated by \`scripts/build-page-index.sh\` from the oe-frontend-tests crawl of
	${version} (${areas} areas, ${pages} pages). **Grep this file, don't read it** -
	it is a lookup table, one row per page:

	    grep -i 'lens type' subs/page-index.md
	    grep '^| admin/core' subs/page-index.md

	\`Route\` is the client-agnostic form and is what belongs in a PR or a ticket;
	\`URL\` is the crawler's concrete example and may embed a sample record id.
	\`Reach\` is the menu path a user follows. A blank \`Reach\` means the page was
	only reached by direct navigation. Pages marked \`(no access)\` returned a
	permission or error page for the crawling user - the address is still correct.

	Field-level detail for these pages lives in \`subs/admin-forms.md\`,
	\`subs/event-forms.md\` and \`subs/app-forms.md\`; the navigation narrative is in
	\`subs/paths.md\`. Screenshots are not vendored - they stay in the crawl output.

	A handful of \`Page\` values contain an em dash. That is the real on-screen title,
	captured verbatim - do NOT sweep it to a hyphen, or the label stops matching the
	app and stops matching a grep for it.

	| Area | Page | Route | URL | Reach |
	|---|---|---|---|---|
	HEADER
}

writeRows() {
    # navPath entries use a non-ASCII separator in the crawl output; fold it to
    # '>' so the file stays plain ASCII and greps cleanly. Pipes inside any field
    # would break the table, so they are escaped.
    jq -r '
        .pages
        | sort_by(.area, .id)
        | .[]
        | [ .area,
            (.title // .id) + (if .accessible == false then " (no access)" else "" end),
            (.route // ""),
            (.url // ""),
            ((.navPath // []) | join(" / "))
          ]
        | map(gsub("\\|"; "\\\\|"))
        | "| " + join(" | ") + " |"
    ' "${sitemap_index}" \
        | sed 's/\xe2\x96\xb8/>/g' \
        >> "${page_index}"
}

##################################################
################# EXECUTION ######################
##################################################

echo "Writing header to ${page_index}..."
writeHeader
echo -e "[Done]\n"

echo "Writing page rows..."
writeRows
echo "  $(grep -c '^| /\|^| [a-z]' "${page_index}") rows written"
echo -e "[Done]\n"

trap : 0
echo >&2 ""
echo "**************************************************"
echo "**************************************************"
echo "***************PAGE INDEX BUILD DONE**************"
echo "**************************************************"
echo "**************************************************"
