#!/bin/bash -l
# Manpreet 23/07/2026
# Entrypoint for the OE Chrome agent container: brings up Xvfb + fluxbox + x11vnc + noVNC,
# launches Chrome against a DISPOSABLE profile, then hands off to Claude Code.
#
# Every start - restart as well as recreate - begins by wiping the container's own state and
# laying a fresh profile back down, so a walk never begins inside the last walk's browser.
# The only things that outlive a boot are the two logins, harvested here before the wipe and
# restored from the kit's state dir (~1KB of JSON): the CLI's /login credential and the
# extension's claude.ai sign-in + site grants. Everything else a Chrome profile accumulates -
# caches, cookies, history, the extension bundle - is regenerable, and the extension bundle in
# particular is baked into the image, so a fresh profile costs a template copy rather than a
# Web Store download.

abort() {
    echo >&2 '
****************************
*** ABORTED DUE TO ERROR ***
****************************
'
    date
    echo "An error occurred. Exiting..." >&2
    exit 1
}

trap 'abort' 0
set -e

##################################################
### VARIABLES (See end of script for execution) ##
##################################################

screen_geometry="${SCREEN_GEOMETRY:-1920x1080x24}"
vnc_port="${VNC_PORT:-5900}"
novnc_port="${NOVNC_PORT:-6080}"
oe_url="${OE_URL:-http://web}"
chrome_kiosk="${CHROME_KIOSK:-0}"
cdp_port="${CDP_PORT:-9222}"
chrome_profile_dir="${HOME}/chrome-profile"
chrome_profile_template="/opt/chrome-profile-template"
state_dir="${HOME}/state"
claude_bin="/usr/local/lib/node_modules/@anthropic-ai/claude-code/bin/claude.exe"
extension_id="fcoeoabgfenejglbffodgkkbkcdhcgfn"
lockdown_policy="/etc/opt/chrome/policies/managed/oe-lockdown.json"

##################################################
### CHECKS (See end of script for execution)    ##
##################################################

echo -e "\nStarting Pre-flight checks ..."
echo "-------------------------------"

echo "Checking claude home is writable..."
[ -w "${HOME}" ] || { echo "${HOME} is not writable"; exit 1; }
echo "[OK]"

echo "Checking artifacts dir is writable..."
mkdir -p "${HOME}/artifacts"
[ -w "${HOME}/artifacts" ] || { echo "${HOME}/artifacts is not writable - was ./artifacts created before 'docker compose up'?"; exit 1; }
echo "[OK]"

echo "Checks complete ..."
echo "-------------------------------"

##################################################
### FUNCTIONS (See end of script for execution) ##
##################################################

harvestSavedLogins() {
    # Runs FIRST, before wipeContainerState. The CLI's refresh token rotates on use and dies
    # 28 days after it was minted, so whatever the last boot refreshed has to be lifted out
    # before the wipe destroys it - otherwise the saved copy silently expires and the walker
    # asks for /login again. This is also the one moment the extension's LevelDB has no lock
    # on it, because Chrome is not running yet. Non-fatal: a first-ever container has nothing
    # to harvest and both halves no-op.
    /usr/local/bin/sync-state.sh -s || echo "  nothing harvested - see above (a first boot has nothing to save)"
}

wipeContainerState() {
    # "Nothing in the container persists except the logins." A container *restart* reuses the
    # same writable layer, so without this the next walk starts inside the last walk's browser
    # and the last walk's Claude Code state - cookies, history, every site grant it collected,
    # transcripts, a stale MCP bridge socket. Everything cleared here is either regenerated by
    # the seed functions below or restored from ${state_dir}.
    # /tmp is cleared by content, keeping .X11-unix itself: the image creates that directory
    # 1777 so Xvfb can bind its socket there as a non-root uid, and a wipe that removed it
    # would leave the recreated one owned wrong. Its stale socket goes with the X lock in /tmp,
    # which is what makes the old display-lock cleanup unnecessary.
    # ${HOME}/artifacts and ${state_dir} are bind mounts and are deliberately not touched.
    rm -rf "${chrome_profile_dir}" \
           "${HOME}/.claude" \
           "${HOME}/.claude.json" \
           "${HOME}/.config" \
           "${HOME}/oe-login.log"
    find /tmp -mindepth 1 -maxdepth 1 ! -name '.X11-unix' -exec rm -rf {} + 2>/dev/null || true
    rm -f "/tmp/.X11-unix/X${DISPLAY#:}"
}

writeLockdownPolicy() {
    # The navigation allowlist - the half of the Chrome policy that can't be baked into the
    # image, because the OE origin is only known at boot from $OE_URL. The container drives one
    # OE instance and nothing else, and it hands a browser to a model that reads whatever an OE
    # page happens to contain, so restricting where that browser can go is the actual mitigation
    # for a prompt injected into a page. No key here appears in the baked policy: Chrome merges
    # the directory and a key set in two files has no defined winner.
    # Non-fatal on an unwritable file - the image ships it as {}, so the fallback is an
    # unrestricted browser rather than one that can reach nothing.
    local oe_host="${oe_url#*://}"
    oe_host="${oe_host%%/*}"
    [ -w "${lockdown_policy}" ] || { echo "  ${lockdown_policy} is not writable - browsing stays unrestricted (rebuild the image)"; return 0; }
    cat > "${lockdown_policy}" <<-JSON
{
  "URLBlocklist": ["*"],
  "URLAllowlist": [
    "${oe_host}",
    "claude.ai",
    "claude.com",
    "anthropic.com",
    "hcaptcha.com",
    "challenges.cloudflare.com",
    "accounts.google.com",
    "accounts.google.co.uk",
    "localhost",
    "127.0.0.1",
    "chrome-extension://${extension_id}",
    "chrome://new-tab-page",
    "chrome://policy",
    "chrome://extensions",
    "about:blank"
  ]
}
JSON
    echo "  navigation restricted to ${oe_host} (plus the sign-in and extension origins)"
}

createChromeProfile() {
    # Laid down unconditionally, on every boot: the profile is the container's memory of the
    # last walk, and this is what makes a restart a full reset rather than a resume. The
    # template is the image's pre-warmed copy (extension already unpacked), so this costs a
    # local copy of ~17M rather than a Web Store download.
    if [ -d "${chrome_profile_template}" ]; then
        cp -a "${chrome_profile_template}" "${chrome_profile_dir}"
        echo "  fresh profile laid down from the baked template"
    else
        mkdir -p "${chrome_profile_dir}"
        echo "  fresh empty profile - no baked template in this image, Chrome will fetch the extension"
    fi
}

restoreClaudeCredentials() {
    # The CLI's /login credential, the one piece of ~/.claude worth outliving a container.
    # Transcripts, caches and plugins are deliberately not kept: this container drives a
    # browser, it isn't where work is authored.
    local src="${state_dir}/claude-credentials.json"
    [ -f "${src}" ] || { echo "  no saved credential - run /login inside the container, then ./save-state.sh"; return 0; }
    [ -f "${HOME}/.claude/.credentials.json" ] && { echo "  credential already present - left alone"; return 0; }
    mkdir -p "${HOME}/.claude"
    cp "${src}" "${HOME}/.claude/.credentials.json"
    chmod 0600 "${HOME}/.claude/.credentials.json"
    echo "  restored the CLI /login credential"
}

seedClaudeState() {
    # Undocumented keys (hasCompletedOnboarding, theme, hasTrustDialogAccepted,
    # claudeInChromeDefaultEnabled, hasCompletedClaudeInChromeOnboarding,
    # cachedChromeExtensionInstalled) - if they drift with a future claude release,
    # this just degrades to the wizard showing once, since the write is skipped once
    # the file exists at all. The three chrome-* keys suppress the interactive
    # "enable Claude in Chrome?" onboarding screen that --chrome alone doesn't skip.
    [ -f "${HOME}/.claude.json" ] && return 0
    cat > "${HOME}/.claude.json" <<-JSON
{
  "hasCompletedOnboarding": true,
  "theme": "dark",
  "claudeInChromeDefaultEnabled": true,
  "hasCompletedClaudeInChromeOnboarding": true,
  "cachedChromeExtensionInstalled": true,
  "projects": {
    "${HOME}": {
      "hasTrustDialogAccepted": true
    }
  }
}
JSON
}

seedClaudeSettings() {
    # Pre-allow the extension's MCP tools so print-mode (claude -p) sessions are not
    # auto-denied at the CLI's permission gate - without this every unattended call
    # needs --allowedTools "mcp__claude-in-chrome" on the command line. Bash/WebFetch/
    # WebSearch are denied outright (not just left unapproved): this container's sole
    # purpose is driving OE through the extension, so direct shell/HTTP access is
    # unneeded attack surface, not a prompt to whitelist away.
    [ -f "${HOME}/.claude/settings.json" ] && return 0
    mkdir -p "${HOME}/.claude"
    cat > "${HOME}/.claude/settings.json" <<-JSON
{
  "permissions": {
    "allow": [
      "mcp__claude-in-chrome",
      "Write(${HOME}/artifacts/**)"
    ],
    "deny": [
      "Bash",
      "WebFetch",
      "WebSearch"
    ]
  }
}
JSON
}

seedNativeMessaging() {
    # The CLI writes these two files only at STARTUP while already logged in, which
    # forced a restart-after-/login dance. Their content is deterministic, so seed
    # them on every boot instead - Chrome can then pair on the very first start.
    mkdir -p "${HOME}/.claude/chrome" "${chrome_profile_dir}/NativeMessagingHosts"
    cat > "${HOME}/.claude/chrome/chrome-native-host" <<-SH
#!/bin/sh
# Chrome native host wrapper script
# Generated by Claude Code - do not edit manually
exec "${claude_bin}" --chrome-native-host
SH
    chmod 0755 "${HOME}/.claude/chrome/chrome-native-host"
    cat > "${chrome_profile_dir}/NativeMessagingHosts/com.anthropic.claude_code_browser_extension.json" <<-JSON
{
  "name": "com.anthropic.claude_code_browser_extension",
  "description": "Claude Code Browser Extension Native Host",
  "path": "${HOME}/.claude/chrome/chrome-native-host",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://${extension_id}/"]
}
JSON
}

seedExtensionState() {
    # Restores the extension's saved claude.ai sign-in and writes its "always allow" grant
    # for OE_URL's origin straight into its LevelDB store (see seed-extension-state.mjs) -
    # must run before startChrome: once Chrome is up it holds that store's file lock.
    # Non-fatal: falls back to a manual sign-in and the one-time approval click documented
    # in docs/chrome-agent.md.
    OE_URL="${oe_url}" EXTENSION_ID="${extension_id}" CHROME_PROFILE_DIR="${chrome_profile_dir}" \
        STATE_FILE="${state_dir}/extension-state.json" \
        node /usr/local/lib/oe-chrome-agent/seed-extension-state.mjs
}

linkDefaultProfilePath() {
    # Chrome 136+ refuses --remote-debugging-port on the default profile dir, and it
    # REALPATHS the --user-data-dir flag first - so the real directory must live at a
    # non-default path (${chrome_profile_dir}, laid down by createChromeProfile) and the default path
    # becomes a symlink onto it: the CLI's hardcoded manifest writes to
    # ~/.config/google-chrome still land in the profile Chrome actually uses.
    mkdir -p "${HOME}/.config"
    # Anything real sitting here is build-time residue owned by another uid, never state
    # worth keeping - the profile it would shadow is disposable by design.
    [ -L "${HOME}/.config/google-chrome" ] || rm -rf "${HOME}/.config/google-chrome" \
        || { echo "cannot replace ${HOME}/.config/google-chrome (owned by another uid) - rebuild the image"; exit 1; }
    ln -sfn "${chrome_profile_dir}" "${HOME}/.config/google-chrome"
}

startDisplay() {
    Xvfb "${DISPLAY}" -screen 0 "${screen_geometry}" -nolisten tcp &
    sleep 1
}

seedFluxboxConfig() {
    # No window-manager title bar on any window: Chrome's own window is sized to
    # exactly fill the screen (see startChrome), so a fluxbox titlebar on top would
    # push its tab strip down past the visible framebuffer instead of just looking
    # untidy. Deterministic content - reseed on every boot, same as native messaging.
    mkdir -p "${HOME}/.fluxbox"
    cat > "${HOME}/.fluxbox/apps" <<-APPS
[app] (name=.*)
  [Deco] {NONE}
[end]
APPS
}

startWindowManager() {
    fluxbox &
}

startVnc() {
    # -listen 127.0.0.1: only websockify (below) is reachable from outside the container -
    # x11vnc itself is never exposed.
    x11vnc -display "${DISPLAY}" -forever -shared -nopw -quiet -listen 127.0.0.1 -rfbport "${vnc_port}" &
}

startNoVnc() {
    websockify --web=/usr/share/novnc "0.0.0.0:${novnc_port}" "127.0.0.1:${vnc_port}" &
}

startChrome() {
    # --no-sandbox: Chrome's setuid sandbox needs a user-namespace privilege this container
    # doesn't grant (same class of failure as codex's bwrap-in-container issue, see
    # knowledge/codex-compatibility.md) - the container boundary is the real sandbox here.
    # --test-type suppresses the resulting "unsupported command-line flag" infobar; it's
    # purely cosmetic (Chrome's own automation-tooling flag for hiding that warning UI) -
    # no sandboxing behaviour changes, --no-sandbox is still in effect underneath.
    # --disable-dev-shm-usage avoids Chrome crashing on Docker's small default /dev/shm.
    # --hide-crash-restore-bubble suppresses the "Restore pages?" prompt from the last
    # unclean kill. --user-data-dir uses the symlink alias (see linkChromeProfileAlias)
    # so Chrome 136+ honours --remote-debugging-port. The CDP port stays inside the
    # container (never published) - oe-login.mjs uses it for OE auto-login.
    local chrome_flags=(
        --no-sandbox
        --test-type
        --disable-dev-shm-usage
        --no-first-run
        --no-default-browser-check
        --hide-crash-restore-bubble
        --password-store=basic
        --user-data-dir="${chrome_profile_dir}"
        --remote-debugging-port="${cdp_port}"
    )
    if [ "${chrome_kiosk}" == "1" ]; then
        chrome_flags+=(--kiosk)
    else
        chrome_flags+=(--window-size=1920,1080 --window-position=0,0)
    fi
    google-chrome-stable "${chrome_flags[@]}" "${oe_url}" &
}

startOeAutoLogin() {
    # Backgrounded: waits for Chrome's CDP endpoint, then submits the OE login form
    # below the extension (Claude in Chrome refuses to type passwords, even sample
    # ones). Non-fatal on failure - the walk just starts at the login page. Chains the
    # extension's options tab open afterward in the same background job, so it isn't
    # one of the "extra" tabs oe-login.mjs's own CDP-startup pass collapses away.
    (
        CDP_PORT="${cdp_port}" node /usr/local/bin/oe-login.mjs
        CDP_PORT="${cdp_port}" EXTENSION_ID="${extension_id}" node /usr/local/bin/open-options-tab.mjs
    ) > "${HOME}/oe-login.log" 2>&1 &
}

##################################################
################# EXECUTION ######################
##################################################

echo "Harvesting the logins this container last refreshed (before anything is wiped)..."
harvestSavedLogins
echo -e "[Done]\n"

echo "Wiping the container's own state so this walk starts clean..."
wipeContainerState
echo -e "[Done]\n"

echo "Laying down the Chrome profile..."
createChromeProfile
echo -e "[Done]\n"

echo "Restoring the saved CLI /login credential..."
restoreClaudeCredentials
echo -e "[Done]\n"

echo "Seeding Claude Code first-run state..."
seedClaudeState
echo -e "[Done]\n"

echo "Seeding Claude Code settings (extension tools pre-allowed)..."
seedClaudeSettings
echo -e "[Done]\n"

echo "Seeding native-messaging manifest + host shim..."
seedNativeMessaging
echo -e "[Done]\n"

echo "Linking default profile path onto the CDP-capable profile dir..."
linkDefaultProfilePath
echo -e "[Done]\n"

echo "Seeding extension sign-in and site permission for ${oe_url}..."
seedExtensionState
echo -e "[Done]\n"

echo "Writing the Chrome navigation lockdown policy..."
writeLockdownPolicy
echo -e "[Done]\n"

echo "Starting Xvfb on ${DISPLAY}..."
startDisplay
echo -e "[Done]\n"

echo "Seeding fluxbox config (no window decorations)..."
seedFluxboxConfig
echo -e "[Done]\n"

echo "Starting fluxbox..."
startWindowManager
echo -e "[Done]\n"

echo "Starting x11vnc on 127.0.0.1:${vnc_port}..."
startVnc
echo -e "[Done]\n"

echo "Starting noVNC on 0.0.0.0:${novnc_port}..."
startNoVnc
echo -e "[Done]\n"

echo "Starting Chrome..."
startChrome
echo -e "[Done]\n"

echo "Starting OE auto-login (background, log: ~/oe-login.log)..."
startOeAutoLogin
echo -e "[Done]\n"

trap : 0
echo "noVNC ready: http://localhost:${novnc_port} (auto-connects and scales)"
exec claude --chrome "$@"
